In [160]:
import pandas as pd
import os
import re
import math
import numpy as np

df = pd.read_csv('immoweb/immowebDataset.csv', encoding='utf-8')
newdf = pd.read_csv('fullDataset.csv')

In [161]:
def square_meters_cleaning_ImmoWeb(df,columns):
    """
    Function converting the square meters data into floats
    : df: DataFrame to clean
    : columns: list of column labels for which the data needs cleaning
    : return: cleaned DataFrame
    """
    for column in columns:
        for index,element in df[[column]].iterrows():
            if isinstance(element[column],str) and "m²" in element[column]:
                df = df.replace(element[column],float(element[column][:-3]))
        return df

In [162]:
print(df.columns.values)

['Unnamed: 0' 'Unnamed: 0.1' 'Ã\x80 partir de' 'AnnÃ©e de construction'
 'Ã\x89tat du bÃ¢timent' 'Nombre de faÃ§ades' 'Parkings intÃ©rieurs'
 'Parkings extÃ©rieurs' 'Visite virtuelle' 'Surface habitable'
 'Surface du salon' 'Type de cuisine' 'Surface de la cuisine' 'Chambres'
 'Surface de la chambre 1' 'Surface de la chambre 2'
 'Surface de la chambre 3' 'Salles de bains' 'Salles de douche'
 'Toilettes' 'Cave' 'Grenier' 'MeublÃ©' 'Surface du terrain'
 "Raccordement Ã\xa0 l'Ã©gout" 'Eau, gaz & Ã©lectricitÃ©'
 'Surface du jardin' 'Surface de la terrasse'
 "Consommation d'Ã©nergie primaire" 'Classe Ã©nergÃ©tique'
 'NumÃ©ro du rapport PEB' 'Emission COâ\x82\x82'
 "Consommation thÃ©orique totale d'Ã©nergie primaire" 'Type de chauffage'
 'Double vitrage' 'Prix' 'Revenu cadastral' 'Immeuble de rapport'
 'Adresse' 'Largeur de la faÃ§ade Ã\xa0 rue'
 'Type dâ\x80\x99environnement' 'Surface de la chambre 4'
 "Surface de l'espace professionnel" 'Largeur du terrain Ã\xa0 rue'
 'Terrasse' 'Type de zone inondable' 'Site internet' 'Surface de bureau'
 'Bureau' 'Surface du grenier' 'Surface constructible totale au sol'
 'Affectation urbanistique la plus rÃ©cente sur la base des dÃ©nominations utilisÃ©es dans le registre des plans'
 'Permis de bÃ¢tir obtenu' 'Autorisation de lotissement'
 "Droit d'achat prioritaire possible"
 'ProcÃ©dure pour violation de la rÃ©glementation urbanistique'
 'Quartier ou lieu-dit' 'Salle Ã\xa0 manger' 'Ascenseur'
 'Accessible aux personnes avec un handicap' 'Parlophone' 'Piscine'
 'Dressing' 'Buanderie' 'Espace professionnel' 'Porte blindÃ©e'
 'Terrain Ã\xa0 front de rue' 'Terrain boisÃ©' 'Terrain arriÃ¨re'
 'Terrain plat' 'Orientation du jardin' 'Orientation de la terrasse'
 'Concierge' 'AccÃ¨s sÃ©curisÃ© / alarme' 'Climatisation'
 'Interphone vidÃ©o' 'Jacuzzi' 'Sauna' 'Internet' 'Pompe Ã\xa0 chaleur'
 'Panneaux photovoltaÃ¯ques' 'Panneaux solaires' 'Chauffe-eau commun'
 'Type de construction' 'Disponible le' 'Jardin' 'Attestation as-built'
 'Surface de la cave'
 'Attestation de conformitÃ© des citernes Ã\xa0 mazout' 'Bouquet'
 'Rente mensuelle' 'Rente indexÃ©e' 'Rente rÃ©versible'
 'Vente en nue propriÃ©tÃ©' 'Nombre de rentiers' 'Ã\x82ge des rentiers'
 'DurÃ©e maximale de la rente' 'Obligation de construire'
 'Combien de feux ouverts ?' 'IsolÃ©' "Nombre d'annexes"
 'Surface de la chambre 5' 'Nom du bien' 'Salon'
 'Informations supplÃ©mentaires' 'RÃ©fÃ©rence externe'
 'Niveau E (performance Ã©nergÃ©tique globale)' 'Charges mensuelles'
 "Nom de l'agent" 'Lieu de la vente' 'SÃ©ance unique'
 'ModalitÃ©s de visite' 'Mise Ã\xa0 prix' 'Description libre du PEB'
 'Ã\x82ge du rentier' 'Valeur du bien' 'Pourcentage louÃ©'
 'Revenu mensuel actuel' 'Séance unique' 'Modalités de visite'
 'À partir de' "Consommation d'énergie primaire" 'Classe énergétique'
 'Numéro du rapport PEB' 'Emission CO?'
 "Consommation théorique totale d'énergie primaire"
 'Permis de bâtir obtenu' 'Mise à prix' 'État du bâtiment'
 'Nombre de façades' 'Parkings intérieurs' 'Type d\x92environnement'
 'Salle à manger' 'Meublé' "Raccordement à l'égout"
 'Eau, gaz & électricité' 'Référence externe' 'Parkings extérieurs'
 'Année de construction' 'Porte blindée'
 'Niveau E (performance énergétique globale)' 'Pompe à chaleur'
 'Panneaux photovoltaïques'
 'Procédure pour violation de la réglementation urbanistique'
 'Affectation urbanistique la plus récente sur la base des dénominations utilisées dans le registre des plans'
 'Largeur de la façade à rue' 'Terrain à front de rue'
 'Largeur du terrain à rue' 'Informations supplémentaires' 'Terrain boisé'
 'Terrain arrière' 'Accès sécurisé / alarme' 'Interphone vidéo'
 'Attestation de conformité des citernes à mazout' 'Isolé' 'Rente indexée'
 'Rente réversible' 'Vente en nue propriété' 'Âge du rentier'
 'Durée maximale de la rente' 'Pourcentage loué' '<<<<<<< HEAD'
 'Date de la vente' 'Vue sur mer' 'Ã\x89tage' "Nombre d'Ã©tages"]

In [156]:
# set immoweb as source for the new files.
newdf['source'] = 'immoweb'
# set address to the column
newdf['Locality'] = df['Adresse']
# TODO 
newdf['Type of property'] = 'TODO'
# TODO 
newdf['Subtype of property'] = 'TODO'
# TODO 
newdf['Price'] = df['Prix']
# TODO 
newdf['Type of sale'] = 'TODO'
# TODO 
newdf['Number of rooms'] = df['Chambres']
# TODO 
newdf['Area'] = df['Surface habitable']
# TODO 
newdf['Fully equipped kitchen'] = df['Type de cuisine']
# TODO 
newdf['Furnished'] = df['Meublé']
# TODO 
newdf['Open fire'] = df['Combien de feux ouverts ?']
# TODO 
newdf['Terrace'] = df['Terrasse']
# TODO 
newdf['Garden'] = df['Surface du jardin']
# TODO 
newdf['Surface area of the plot of land'] = df['Surface du terrain']
# TODO 
newdf['Number of facades'] = df['Nombre de façades']
# TODO 
newdf['Swimming pool'] = df['Piscine']
# TODO 
newdf['State of the building'] = df['État du bâtiment']

KeyError: 'Meublé'

In [153]:
square_meters_cleaning_ImmoWeb(newdf, ['Area', 'Fully equipped kitchen', 'Garden', 'Surface area of the plot of land'])

,Source,Locality,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Area,Fully equipped kitchen,Furnished,Open fire,Terrace,Garden,Surface of the land,Surface area of the plot of land,Number of facades,Swimming pool,State of the building,source
0,NaN,4528872,TODO,TODO,396 â¬,TODO,12 mÂ²,30 mÂ²,12 mÂ²,NaN,NaN,NaN,50 mÂ²,NaN,ConnectÃ©,NaN,NaN,NaN,immoweb
1,NaN,Trekschurenstraat 245\r\n3500 - Hasselt,TODO,TODO,NaN,TODO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,immoweb
2,NaN,Nieuwstraat 32b1\r\n1730 - Asse,TODO,TODO,349.000 â¬,TODO,4,200 mÂ²,Semi-Ã©quipÃ©e,NaN,NaN,Oui,NaN,NaN,647 mÂ²,NaN,NaN,NaN,immoweb
3,NaN,116 boulevard d'Avroy\r\n4000 - LiÃ¨ge,TODO,TODO,350.000 â¬,TODO,3,190 mÂ²,ÃquipÃ©e,NaN,NaN,NaN,1458 mÂ²,NaN,1612 mÂ²,NaN,NaN,NaN,immoweb
4,NaN,Brusselbaan 110\r\n1790 - Affligem,TODO,TODO,389.000 â¬,TODO,3,132 mÂ²,ÃquipÃ©e,NaN,NaN,Oui,100 mÂ²,NaN,317 mÂ²,NaN,NaN,NaN,immoweb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10007,NaN,Avenue Capouillet 58 A\r\n1410 - Waterloo,TODO,TODO,1.950.000 â¬,TODO,6,1280 mÂ²,Hyper Ã©quipÃ©e,NaN,NaN,NaN,NaN,NaN,3723 mÂ²,NaN,NaN,NaN,immoweb
10008,NaN,NaN,TODO,TODO,542 â¬,TODO,22 mÂ²,23 mÂ²,19 mÂ²,NaN,NaN,Sud-ouest,NaN,NaN,ConnectÃ©,NaN,NaN,NaN,immoweb
10009,NaN,ChaussÃ©e de Bruxelles 23 (sur N5)\r\n1472 - V...,TODO,TODO,Faire offre Ã partir de 300.000 â¬,TODO,3,170 mÂ²,NaN,NaN,NaN,NaN,NaN,NaN,513 mÂ²,NaN,NaN,NaN,immoweb
10010,NaN,NaN,TODO,TODO,Non,TODO,34 mÂ²,41 mÂ²,30 mÂ²,NaN,NaN,393 kWh/mÂ²,NaN,NaN,ConnectÃ©,NaN,NaN,NaN,immoweb
10011,NaN,"Rue des Saules, 31\r\n1380 - Ohain",TODO,TODO,350.000 â¬,TODO,3,145 mÂ²,ÃquipÃ©e,NaN,NaN,Oui,NaN,NaN,1523 mÂ²,NaN,NaN,NaN,immoweb

In [135]:
for index, row in newdf.iterrows():
    try:
        num = int(row['Locality'])
        val = None
    except:
        val = row['Locality']    
    newdf.at[index,'Locality'] = val

for index, row in newdf.iterrows():
    try:
        num = int(row['Number of rooms'])
        val = num
    except:
        val = 'None'    
    newdf.at[index,'Number of rooms'] = val
    
for index, row in newdf.iterrows():
    val = row['Open fire']
    if pd.isna(val):
        val = 0
    else:
        val = 1   
    newdf.at[index,'Open fire'] = val
    
for index, row in newdf.iterrows():
    val = row['Furnished']
    if pd.isna(val):
        val = 0
    else:
        val = 1   
    newdf.at[index,'Furnished'] = val
    
for index, row in newdf.iterrows():
    val = row['Swimming pool']
    if pd.isna(val):
        val = 0
    else:
        val = 1   
    newdf.at[index,'Swimming pool'] = val
    
for index, row in newdf.iterrows():
    try:
        num = int(row['Number of facades'])
        val = num
    except:
        val = 'None'    
    newdf.at[index,'Number of facades'] = val
    
for index, row in newdf.iterrows():
    state = str(row['State of the building'])
    if 'Bon' in state or 'Excellent' in state or 'rénové' in state:
        val = 'Good'
    elif 'rénover' in state or 'rafraîchir' in state:
        val = 'Poor'
    else:
        val = 'None'
    newdf.at[index,'State of the building'] = val
    
for index, row in newdf.iterrows():
    val = row['Terrace']
    if str(val) == 'Oui':
        val = 1
    else:
        val = 0   
    newdf.at[index,'Terrace'] = val
    
for index, row in newdf.iterrows():

396

ValueError: invalid literal for int() with base 10: ''

In [137]:
print(newdf)

      Source                                           Locality  \
0        NaN                                               None
1        NaN            Trekschurenstraat 245\r\n3500 - Hasselt
2        NaN                    Nieuwstraat 32b1\r\n1730 - Asse
3        NaN             116 boulevard d'Avroy\r\n4000 - LiÃ¨ge
4        NaN                 Brusselbaan 110\r\n1790 - Affligem
...      ...                                                ...
10007    NaN          Avenue Capouillet 58 A\r\n1410 - Waterloo
10008    NaN                                                NaN
10009    NaN  ChaussÃ©e de Bruxelles 23 (sur N5)\r\n1472 - V...
10010    NaN                                                NaN
10011    NaN                 Rue des Saules, 31\r\n1380 - Ohain

      Type of property Subtype of property  \
0                 TODO                TODO
1                 TODO                TODO
2                 TODO                TODO
3                 TODO                TODO
4                 TODO                TODO
...                ...                 ...
10007             TODO                TODO
10008             TODO                TODO
10009             TODO                TODO
10010             TODO                TODO
10011             TODO                TODO

                                      Price Type of sale Number of rooms  \
0                                       396         TODO            None
1                                       NaN         TODO            None
2                               349.000 â¬         TODO               4
3                               350.000 â¬         TODO               3
4                               389.000 â¬         TODO               3
...                                     ...          ...             ...
10007                         1.950.000 â¬         TODO               6
10008                               542 â¬         TODO            None
10009  Faire offre Ã  partir de 300.000 â¬         TODO               3
10010                                   Non         TODO            None
10011                           350.000 â¬         TODO               3

           Area Fully equipped kitchen Furnished Open fire Terrace    Garden  \
0        30 mÂ²                 12 mÂ²         1         1       0    50 mÂ²
1           NaN                    NaN         1         1       0       NaN
2       200 mÂ²         Semi-Ã©quipÃ©e         1         1       0       NaN
3       190 mÂ²              ÃquipÃ©e         1         1       0  1458 mÂ²
4       132 mÂ²              ÃquipÃ©e         1         1       0   100 mÂ²
...         ...                    ...       ...       ...     ...       ...
10007  1280 mÂ²        Hyper Ã©quipÃ©e         1         1       0       NaN
10008    23 mÂ²                 19 mÂ²         1         1       0       NaN
10009   170 mÂ²                    NaN         1         1       0       NaN
10010    41 mÂ²                 30 mÂ²         1         1       0       NaN
10011   145 mÂ²              ÃquipÃ©e         1         1       0       NaN

      Surface of the land Surface area of the plot of land Number of facades  \
0                     NaN                        ConnectÃ©              None
1                     NaN                              NaN              None
2                     NaN                          647 mÂ²              None
3                     NaN                         1612 mÂ²              None
4                     NaN                          317 mÂ²              None
...                   ...                              ...               ...
10007                 NaN                         3723 mÂ²              None
10008                 NaN                        ConnectÃ©              None
10009                 NaN                          513 mÂ²              None
10010                 NaN                        ConnectÃ©              None
10011                 NaN                         1523 mÂ²              None

      Swimming pool State of the building source
0                 1                  None    NaN
1                 1                  None    NaN
2                 1                  None    NaN
3                 1                  None    NaN
4                 1                  None    NaN
...             ...                   ...    ...
10007             1                  None    NaN
10008             1                  None    NaN
10009             1                  None    NaN
10010             1                  None    NaN
10011             1                  None    NaN

[10012 rows x 19 columns]

In [ ]:
# TODO 
#newdf['Surface of the land'] = df['Surface du terrain'] - df['Surface du jardin']